### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by isaacrg** [netlify/netlify-cms#33]
Recent updates appear to have broken netlify-cms in some way. I am getting on the error below on https://moonsquads.netlify.com/admin/

```text
Error while processing route: index.list Cannot read property 'loadEntries' of undefined TypeError: Cannot read property 'loadEntries' of undefined
    at loadEntries (https://cms.netlify.com/assets/cms.js:2405:29)
    at prepare (https://cms.netlify.com/assets/cms.js:2399:12)
    at setupController (https://cms.netlify.com/assets/cms.js:4160:18)
    at superWrapper [as setupController] (https://cms.netlify.com/assets/vendor.js:30338:22)
    at _emberRuntimeSystemObject.default.extend.setup (https://cms.netlify.com/assets/vendor.js:35136:12)
    at Object.callHook (https://cms.netlify.com/assets/vendor.js:58320:38)
    at handlerEnteredOrUpdated (https://cms.netlify.com/assets/vendor.js:57100:12)
    at setupContexts (https://cms.netlify.com/assets/vendor.js:57068:9)
    at finalizeTransition (https://cms.netlify.com/assets/vendor.js:57246:7)
    at https://cms.netlify.com/assets/vendor.js:56681:14
```

**Comment by isaacrg** [comment]
Spoke too soon. Error was caused by Jekyll processing the yaml, I think.

Anyway, its fixed.
