### ISSUE TITLE
Timeout uploading large files

### ISSUE THREAD

**Issue by FTWinston** [netlify/netlify-cms#4538]
**Describe the bug**
When uploading a large media file to a new post, the upload repeatedly times out after 60s.
As it's a big file (~50MB), I'd expect the upload to take longer than 60s, but the CMSs repeatedly aborts and retries after 60s.
It looks like this is intentional, perhaps caused by #3649?

Console output below:
```
Pausing requests for 4 seconds due to fetch failures: Request timed out after 60 seconds
cms.js:118591 Done pausing requests
cms.js:118589 Pausing requests for 9 seconds due to fetch failures: Request timed out after 60 seconds
cms.js:118591 Done pausing requests
cms.js:118589 Pausing requests for 16 seconds due to fetch failures: Request timed out after 60 seconds
react_devtools_backend.js:2450 leave called too many times.
cms.js:118591 Done pausing requests
cms.js:118589 Pausing requests for 25 seconds due to fetch failures: Request timed out after 60 seconds
react_devtools_backend.js:2450 leave called too many times.
cms.js:118591 Done pausing requests
react_devtools_backend.js:2450 API_ERROR: Request timed out after 60 seconds
    at new t (cms.js:53893:25)
    at i._createSuperInternal (cms.js:796:283)
    at new i (cms.js:53886:27)
    at E.handleRequestError (cms.js:54745:17)
    at E._callee69$ (cms.js:54804:61)
    at tryCatch (cms.js:223192:40)
    at Generator.invoke [as _invoke] (cms.js:223421:22)
    at Generator.prototype.<computed> [as throw] (cms.js:223244:21)
    at asyncGeneratorStep (cms.js:223885:24)
    at _throw (cms.js:223911:9)

cms.js:223888 Uncaught (in promise) {type: "ENTRY_PERSIST_FAILURE", error: "Failed to persist entry", payload: {…}}
```

**To Reproduce**
1. Go to the CMS, add a new content entry, of a type with a "file" field.
2. Click "choose a file", then "upload" and pick a large file.
3. Save the entry, wait a few minutes.
4. See error.

**Expected behavior**
Saving should eventually succeed.

**Applicable Versions:**
 - netlify-cms-app: 2.13.1
 - netlify-cms-core: 2.33.1
 - netlify-cms: 2.10.66
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version chrome 86

**CMS configuration**
[config.yml](https://github.com/FTWinston/bvp/blob/master/static/admin/config.yml)

**Additional context**
If [this timeout](https://github.com/netlify/netlify-cms/pull/3649/files#diff-09e74c3942d1da38115b615f80c9b97f07a86d794548fe465b94e4db4148c7c3R13) were configurable, or could be disabled when uploading files, that would seem to me to prevent this problem.

Alternatively, if this is simply a much larger file than I ought to be storing in the CMS, then by all means tell me that.

Thanks in advance!

**Comment by erezrokah** [comment]
Thanks @FTWinston, maybe it would be a good idea to have an increased default timeout for `POST` requests and also make it configurable.

**Comment by FTWinston** [comment]
Either of those sound good to me. Both sound great!

**Comment by KancerEzeroglu** [comment]
I'm going to work on this issue 🎉

**Comment by KancerEzeroglu** [comment]
Hi,

I changed the timeout to 120 in the unsentRequest.js file.

https://github.com/KancerEzeroglu/netlify-cms/blob/b749cd7ddde98b5dda2e4b3ddd0deff9c1fc7571/packages/netlify-cms-lib-util/src/unsentRequest.js#L13

Then I start getting the error below: 

<img width="1898" alt="Screen Shot 2020-12-01 at 11 42 37" src="https://user-images.githubusercontent.com/1583507/100732623-44c4ea00-33cd-11eb-8846-35549cbecfee.png">

It's coming directly from GitHub and I couldn't find the root cause. 
How should we proceed?

**Comment by TristanSchorn** [comment]
@KancerEzeroglu I found [this](https://stackoverflow.com/a/29982303/3259567) which seems to imply this is an HTTP post buffer size limitation. Is it possible to reduce the buffer Netlify CMS uses?

**Comment by KancerEzeroglu** [comment]
Hi,

I played with timeouts on our side but I still got errors from Github API, for me, it seems there are some limitations on the Github site.
I couldn't find any option to set timeout and/or buffer size in the APIs.

As an improvement, we can show a more user-friendly error instead of logging an error to the console. @erezrokah wdyt?

**Comment by erezrokah** [comment]
I missed the last comment on this issue.

If someone would like to pick this up, it would be great to share the error received from GitHub when we increase the timeout, and possibly report it to GitHub's support to see if that's expected.

As for ⬇️ 
>@KancerEzeroglu I found this which seems to imply this is an HTTP post buffer size limitation. Is it possible to reduce the buffer Netlify CMS uses?

The CMS doesn't use `git` directly, so that setting is not relevant for the CMS

**Comment by modi98** [comment]
Has there been any update on this issue? I'm also getting this error on Gitlab, I've already tried updating the CMS to the latest version and adding Large Media to see if that helps but still the request times out before completing.

**Comment by tulsileathers** [comment]
I'm also experiencing this timeout with gitlab

**Comment by tulsileathers** [comment]
I could take a look at fixing it if someone pointed me in the right direction. Haven't looked at the netlify-cms code base before

**Comment by arm1n** [comment]
If I understand the Github docs regarding large files correctly, file uploads (via browsers) are limited to 25MB only: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#about-size-limits-on-github
