### ISSUE TITLE
React PropTypes error: `Warning: Failed prop type: invariant is not defined`

### ISSUE THREAD

**Issue by mikestopcontinues** [netlify/netlify-cms#5347]
**Describe the bug**

I recently upgraded a bunch of packages, and I find I'm getting this error. A bit of googling leads me to think it's got to do with React PropTypes being used funny. It's not a critical bug, as it doesn't keep the CMS from running, but it's worth noting...

**To Reproduce**

Install the packages below and start it up...

```
netlify-cms-app.v2.15.2.js:569 netlify-cms-app 2.15.2
netlify-cms-app.v2.15.2.js:167 netlify-cms-core 2.40.0
react_devtools_backend.js:2557 Warning: Failed prop type: invariant is not defined
    at D (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:220:5917)
    at E (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:43:36201)
    at t (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:54:24007)
    at t (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:54:20538)
    at w (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:207:66071)
    at l (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:199:71241)
    at https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:167:232807
    at E (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:43:36201)
    at d (https://localhost:3011/_snowpack/pkg/netlify-cms-app.v2.15.2.js:43:34257)
overrideMethod @ react_devtools_backend.js:2557
printWarning @ react.v17.0.2.js:223
error @ react.v17.0.2.js:199
checkPropTypes @ react.v17.0.2.js:1938
validatePropTypes @ react.v17.0.2.js:2139
createElementWithValidation @ react.v17.0.2.js:2243
(anonymous) @ netlify-cms-app.v2.15.2.js:199
updateContextConsumer @ react-dom.v17.0.2.js:18751
beginWork @ react-dom.v17.0.2.js:19118
beginWork$1 @ react-dom.v17.0.2.js:23933
performUnitOfWork @ react-dom.v17.0.2.js:22769
workLoopSync @ react-dom.v17.0.2.js:22700
renderRootSync @ react-dom.v17.0.2.js:22663
performSyncWorkOnRoot @ react-dom.v17.0.2.js:22286
scheduleUpdateOnFiber @ react-dom.v17.0.2.js:21874
updateContainer @ react-dom.v17.0.2.js:25475
(anonymous) @ react-dom.v17.0.2.js:26010
unbatchedUpdates @ react-dom.v17.0.2.js:22424
legacyRenderSubtreeIntoContainer @ react-dom.v17.0.2.js:26009
render @ react-dom.v17.0.2.js:26092
_ @ netlify-cms-app.v2.15.2.js:167
(anonymous) @ index.js:22
Promise.then (async)
(anonymous) @ index.js:22
rollbar.min.js:1  Nice to see you here! Wanna play a Cloudinary game?  To start it, you'll have to cheat like John Carmack.

```

**Expected behavior**

No errors.

**Applicable Versions:**

 - Netlify CMS version:
   - netlify-cms-app: 2.15.2
   - netlify-cms-core: 2.40.0
 - React/Dom: 17.0.2
 - Git provider: Github
 - OS: OSX 11.2.3
 - Browser version: Chrome 90
 - Node.JS version: 14.16.1

**Comment by mikestopcontinues** [comment]
The error seems to be with `-app`, not the regular package. I switched back to importing `netlify-cms` from the cdn, and the error is gone.
