### ISSUE TITLE
Error: Cannot resolve a DOM node from Slate node: {"text":""}

### ISSUE THREAD

**Issue by thejenfarmersays** [netlify/netlify-cms#7316]
**Describe the bug**
Error: Cannot resolve a DOM node from Slate node: {"text":""} at Object.toDOMNode (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2629370) at Object.toDOMPoint (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2629524) at Object.toDOMRange (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2630314) at r (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2660407) at https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2660711 at il (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2207195) at _l (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2214449) at wl (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2214295) at bl (https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2213833) at https://cdn.jsdelivr.net/npm/decap-cms@3.1.2/dist/decap-cms.js:485:2225613

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.2`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: community-phone-company/website
  branch: main
  base_url: https://cms-oauth-proxy.vercel.app
  auth_endpoint: /auth
  site_domain: https://www.communityphone.org
publish_mode: editorial_workflow
media_folder: public/img/blog/images
public_folder: /img/blog/images
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Excerpt
        name: excerpt
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Featured
        name: featured
        widget: boolean
        default: false
      - label: Thumbnail
        name: thumbnail
        widget: image
        choose_url: true
        media_library:
          config:
            multiple: false
        required: false
      - label: Meta Title
        name: metaTitle
        widget: string
        required: false
      - label: Meta Description
        name: metaDescription
        widget: string
        required: false
      - label: Meta Keywords
        name: keywords
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: CTA Group
        name: ctaGroup
        widget: select
        options:
          - consumer
          - business
        default: consumer
      - label: Tags
        name: tags
        widget: relation
        collection: tags
        search_fields:
          - title
        value_field: title
        display_fields:
          - title
        multiple: true
        required: false
      - label: Authors
        name: authors
        widget: list
        default: []
        field:
          label: Author
          name: author
          widget: select
          options:
            - ellie
            - james
            - mark
            - logan
        required: false
      - label: Editors
        name: editors
        widget: list
        default: []
        field:
          label: Editor
          name: editor
          widget: select
          options:
            - ellie
            - james
            - mark
            - logan
        required: false
      - label: Updated At
        name: updatedAt
        widget: datetime
        required: false
      - label: Index
        name: index
        widget: boolean
        default: true
      - label: Sidebar Visible
        name: isSidebarVisible
        widget: boolean
        default: true
      - label: See All Posts Visible
        name: isSeeAllPostsVisible
        widget: boolean
        default: true
      - label: Bottom CTA Visible
        name: isBottomCtaVisible
        widget: boolean
        default: true
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
  - name: tags
    label: Tags
    folder: blog/tags
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
    view_filters: []
    view_groups: []
  - name: lander
    label: Lander
    folder: content/landers
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    identifier_field: pageName
    nested:
      depth: 100
      summary: "{{pageName}}"
    meta:
      path:
        widget:
...

**Comment by yanthomasdev** [comment]
Hey @thejenfarmersays, thanks for reporting the error. This should now be fixed in the new Richtext editor: 
https://decapcms.org/blog/richtext-widget-replaces-markdown-widget/
